#Channel 0
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[0]: !<value> 0
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0.99446
        - IntegrationScaling[1]: !<value> 1
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[0]: !<value> 0.999998
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0
        - IntegrationScaling[1]: !<value> 1
