#Channel 0 CBLM:UNDH:4775
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[0]: !<value> 0
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0.99446
        - IntegrationScaling[1]: !<value> 1
        - triggerDelayPeak[0]: !<value> 1563
        - triggerWidthPeak[0]: !<value> 18
        - triggerDelayPedestal[0]: !<value> 61390
        - triggerWidthPedestal[0]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[0]: !<value> 0.999998
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0
        - IntegrationScaling[1]: !<value> 1
        - triggerDelayPeak[0]: !<value> 18
        - triggerWidthPeak[0]: !<value> 18
        - triggerDelayPedestal[0]: !<value> 123
        - triggerWidthPedestal[0]: !<value> 18
