#Channel 0
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[0]: !<value> 1
        - IntegrationCounts[0]: !<value> 2
        - IntegrationCounts[1]: !<value> 179
        - IntegrationCounts[2]: !<value> 0
        - IntegrationCounts[3]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[0]: !<value> 1
        - IntegrationCounts[0]: !<value> 10
        - IntegrationCounts[1]: !<value> 0
        - IntegrationCounts[2]: !<value> 0
        - IntegrationCounts[3]: !<value> 0
#Channel 1
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[1]: !<value> 1
        - IntegrationCounts[4]: !<value> 2
        - IntegrationCounts[5]: !<value> 179
        - IntegrationCounts[6]: !<value> 0
        - IntegrationCounts[7]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[1]: !<value> 1
        - IntegrationCounts[4]: !<value> 10
        - IntegrationCounts[5]: !<value> 0
        - IntegrationCounts[6]: !<value> 0
        - IntegrationCounts[7]: !<value> 0
#Channel 2
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[2]: !<value> 1
        - IntegrationCounts[8]: !<value> 2
        - IntegrationCounts[9]: !<value> 179
        - IntegrationCounts[10]: !<value> 0
        - IntegrationCounts[11]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[2]: !<value> 1
        - IntegrationCounts[8]: !<value> 10
        - IntegrationCounts[9]: !<value> 0
        - IntegrationCounts[10]: !<value> 0
        - IntegrationCounts[11]: !<value> 0
#Channel 3
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[3]: !<value> 1
        - IntegrationCounts[12]: !<value> 2
        - IntegrationCounts[13]: !<value> 179
        - IntegrationCounts[14]: !<value> 0
        - IntegrationCounts[15]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[3]: !<value> 1
        - IntegrationCounts[12]: !<value> 10
        - IntegrationCounts[13]: !<value> 0
        - IntegrationCounts[14]: !<value> 0
        - IntegrationCounts[15]: !<value> 0
#Channel 4
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[4]: !<value> 1
        - IntegrationCounts[16]: !<value> 2
        - IntegrationCounts[17]: !<value> 179
        - IntegrationCounts[18]: !<value> 0
        - IntegrationCounts[19]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[4]: !<value> 1
        - IntegrationCounts[16]: !<value> 10
        - IntegrationCounts[17]: !<value> 0
        - IntegrationCounts[18]: !<value> 0
        - IntegrationCounts[19]: !<value> 0
#Channel 5
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[5]: !<value> 1
        - IntegrationCounts[20]: !<value> 2
        - IntegrationCounts[21]: !<value> 179
        - IntegrationCounts[22]: !<value> 0
        - IntegrationCounts[23]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[5]: !<value> 1
        - IntegrationCounts[20]: !<value> 10
        - IntegrationCounts[21]: !<value> 0
        - IntegrationCounts[22]: !<value> 0
        - IntegrationCounts[23]: !<value> 0