#Channel 1 CBLM:UNDS:3410
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[2]: !<value> 0
        - IntegrationScaling[2]: !<value> 1
        - IntegrationDecay[3]: !<value> 0.99446
        - IntegrationScaling[3]: !<value> 1
        - triggerDelayPeak[1]: !<value> 1547
        - triggerWidthPeak[1]: !<value> 88
        - triggerDelayPedestal[1]: !<value> 61390
        - triggerWidthPedestal[1]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[2]: !<value> 0.999998
        - IntegrationScaling[2]: !<value> 1
        - IntegrationDecay[3]: !<value> 0
        - IntegrationScaling[3]: !<value> 1
        - triggerDelayPeak[1]: !<value> 20
        - triggerWidthPeak[1]: !<value> 18
        - triggerDelayPedestal[1]: !<value> 123
        - triggerWidthPedestal[1]: !<value> 18
#Channel 2 CBLM:UNDS:3510
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[4]: !<value> 0
        - IntegrationScaling[4]: !<value> 1
        - IntegrationDecay[5]: !<value> 0.99446
        - IntegrationScaling[5]: !<value> 1
        - triggerDelayPeak[2]: !<value> 1545
        - triggerWidthPeak[2]: !<value> 88
        - triggerDelayPedestal[2]: !<value> 61390
        - triggerWidthPedestal[2]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[4]: !<value> 0.999998
        - IntegrationScaling[4]: !<value> 1
        - IntegrationDecay[5]: !<value> 0
        - IntegrationScaling[5]: !<value> 1
        - triggerDelayPeak[2]: !<value> 25
        - triggerWidthPeak[2]: !<value> 18
        - triggerDelayPedestal[2]: !<value> 123
        - triggerWidthPedestal[2]: !<value> 18
#Channel 3 CBLM:UNDS:3610
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[6]: !<value> 0
        - IntegrationScaling[6]: !<value> 1
        - IntegrationDecay[7]: !<value> 0.99446
        - IntegrationScaling[7]: !<value> 1
        - triggerDelayPeak[3]: !<value> 1547
        - triggerWidthPeak[3]: !<value> 88
        - triggerDelayPedestal[3]: !<value> 61390
        - triggerWidthPedestal[3]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[6]: !<value> 0.999998
        - IntegrationScaling[6]: !<value> 1
        - IntegrationDecay[7]: !<value> 0
        - IntegrationScaling[7]: !<value> 1
        - triggerDelayPeak[3]: !<value> 16
        - triggerWidthPeak[3]: !<value> 18
        - triggerDelayPedestal[3]: !<value> 123
        - triggerWidthPedestal[3]: !<value> 18
#Channel 4 CBLM:UNDS:3710
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[8]: !<value> 0
        - IntegrationScaling[8]: !<value> 1
        - IntegrationDecay[9]: !<value> 0.99446
        - IntegrationScaling[9]: !<value> 1
        - triggerDelayPeak[4]: !<value> 1545
        - triggerWidthPeak[4]: !<value> 88
        - triggerDelayPedestal[4]: !<value> 61390
        - triggerWidthPedestal[4]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[8]: !<value> 0.999998
        - IntegrationScaling[8]: !<value> 1
        - IntegrationDecay[9]: !<value> 0
        - IntegrationScaling[9]: !<value> 1
        - triggerDelayPeak[4]: !<value> 18
        - triggerWidthPeak[4]: !<value> 18
        - triggerDelayPedestal[4]: !<value> 123
        - triggerWidthPedestal[4]: !<value> 18
#Channel 5 CBLM:UNDS:3810
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[10]: !<value> 0
        - IntegrationScaling[10]: !<value> 1
        - IntegrationDecay[11]: !<value> 0.99446
        - IntegrationScaling[11]: !<value> 1
        - triggerDelayPeak[5]: !<value> 1545
        - triggerWidthPeak[5]: !<value> 88
        - triggerDelayPedestal[5]: !<value> 61390
        - triggerWidthPedestal[5]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[10]: !<value> 0.999998
        - IntegrationScaling[10]: !<value> 1
        - IntegrationDecay[11]: !<value> 0
        - IntegrationScaling[11]: !<value> 1
        - triggerDelayPeak[5]: !<value> 21
        - triggerWidthPeak[5]: !<value> 18
        - triggerDelayPedestal[5]: !<value> 123
        - triggerWidthPedestal[5]: !<value> 18