# Disable all thresholds
- AmcCarrierCore:
  - AppMps:
    - AppMpsRegAppCh:
      - channel:
        - idleEn: !<value> 0x0
        - lcls1Thr:
          - minEn: !<value> 0x0
          - maxEn: !<value> 0x0
          - min:   !<value> 0x0
          - max:   !<value> 0x0
        - stdThr:
          - minEn: !<value> 0x0
          - maxEn: !<value> 0x0
          - min:   !<value> 0x0
          - max:   !<value> 0x0
        - idleThr:
          - minEn: !<value> 0x0
          - maxEn: !<value> 0x0
          - min:   !<value> 0x0
          - max:   !<value> 0x0
        - altThr:
          - minEn: !<value> 0x0
          - maxEn: !<value> 0x0
          - min:   !<value> 0x0
          - max:   !<value> 0x0
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - PrcValueSelect: !<value> 3
      - MpsAnalogLcls2Reg:
        - PrcValueSelect: !<value> 3
# Analog Processing Settings
# Default all channels to No Processing
# Default all Integrators to 1 scaling and 
# 0 decay
#Channel 0
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[0]: !<value> 0
        - IntegrationCounts[0]: !<value> 0
        - IntegrationCounts[1]: !<value> 0
        - IntegrationCounts[2]: !<value> 0
        - IntegrationCounts[3]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[0]: !<value> 0
        - IntegrationCounts[0]: !<value> 0
        - IntegrationCounts[1]: !<value> 0
        - IntegrationCounts[2]: !<value> 0
        - IntegrationCounts[3]: !<value> 0
#Channel 1
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[1]: !<value> 0
        - IntegrationCounts[4]: !<value> 0
        - IntegrationCounts[5]: !<value> 0
        - IntegrationCounts[6]: !<value> 0
        - IntegrationCounts[7]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[1]: !<value> 0
        - IntegrationCounts[4]: !<value> 0
        - IntegrationCounts[5]: !<value> 0
        - IntegrationCounts[6]: !<value> 0
        - IntegrationCounts[7]: !<value> 0
#Channel 2
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[2]: !<value> 0
        - IntegrationCounts[8]: !<value> 0
        - IntegrationCounts[9]: !<value> 0
        - IntegrationCounts[10]: !<value> 0
        - IntegrationCounts[11]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[2]: !<value> 0
        - IntegrationCounts[8]: !<value> 0
        - IntegrationCounts[9]: !<value> 0
        - IntegrationCounts[10]: !<value> 0
        - IntegrationCounts[11]: !<value> 0
#Channel 3
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[3]: !<value> 0
        - IntegrationCounts[12]: !<value> 0
        - IntegrationCounts[13]: !<value> 0
        - IntegrationCounts[14]: !<value> 0
        - IntegrationCounts[15]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[3]: !<value> 0
        - IntegrationCounts[12]: !<value> 0
        - IntegrationCounts[13]: !<value> 0
        - IntegrationCounts[14]: !<value> 0
        - IntegrationCounts[15]: !<value> 0
#Channel 4
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[4]: !<value> 0
        - IntegrationCounts[16]: !<value> 0
        - IntegrationCounts[17]: !<value> 0
        - IntegrationCounts[18]: !<value> 0
        - IntegrationCounts[19]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[4]: !<value> 0
        - IntegrationCounts[16]: !<value> 0
        - IntegrationCounts[17]: !<value> 0
        - IntegrationCounts[18]: !<value> 0
        - IntegrationCounts[19]: !<value> 0
#Channel 5
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - ProcessingSelect[5]: !<value> 0
        - IntegrationCounts[20]: !<value> 0
        - IntegrationCounts[21]: !<value> 0
        - IntegrationCounts[22]: !<value> 0
        - IntegrationCounts[23]: !<value> 0
      - MpsAnalogLcls2Reg:
        - ProcessingSelect[5]: !<value> 0
        - IntegrationCounts[20]: !<value> 0
        - IntegrationCounts[21]: !<value> 0
        - IntegrationCounts[22]: !<value> 0
        - IntegrationCounts[23]: !<value> 0