#Channel 0 CBLM:UNDH:3375
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[0]: !<value> 0
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0.99446
        - IntegrationScaling[1]: !<value> 1
        - triggerDelayPeak[0]: !<value> 1556
        - triggerWidthPeak[0]: !<value> 88
        - triggerDelayPedestal[0]: !<value> 61390
        - triggerWidthPedestal[0]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[0]: !<value> 0.999998
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0
        - IntegrationScaling[1]: !<value> 1
        - triggerDelayPeak[0]: !<value> 21
        - triggerWidthPeak[0]: !<value> 18
        - triggerDelayPedestal[0]: !<value> 123
        - triggerWidthPedestal[0]: !<value> 18
#Channel 1 CBLM:UNDH:3475
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[2]: !<value> 0
        - IntegrationScaling[2]: !<value> 1
        - IntegrationDecay[3]: !<value> 0.99446
        - IntegrationScaling[3]: !<value> 1
        - triggerDelayPeak[1]: !<value> 1556
        - triggerWidthPeak[1]: !<value> 88
        - triggerDelayPedestal[1]: !<value> 61390
        - triggerWidthPedestal[1]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[2]: !<value> 0.999998
        - IntegrationScaling[2]: !<value> 1
        - IntegrationDecay[3]: !<value> 0
        - IntegrationScaling[3]: !<value> 1
        - triggerDelayPeak[1]: !<value> 21
        - triggerWidthPeak[1]: !<value> 18
        - triggerDelayPedestal[1]: !<value> 123
        - triggerWidthPedestal[1]: !<value> 18
#Channel 2 CBLM:UNDH:3575
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[4]: !<value> 0
        - IntegrationScaling[4]: !<value> 1
        - IntegrationDecay[5]: !<value> 0.99446
        - IntegrationScaling[5]: !<value> 1
        - triggerDelayPeak[2]: !<value> 1554
        - triggerWidthPeak[2]: !<value> 88
        - triggerDelayPedestal[2]: !<value> 61390
        - triggerWidthPedestal[2]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[4]: !<value> 0.999998
        - IntegrationScaling[4]: !<value> 1
        - IntegrationDecay[5]: !<value> 0
        - IntegrationScaling[5]: !<value> 1
        - triggerDelayPeak[2]: !<value> 21
        - triggerWidthPeak[2]: !<value> 18
        - triggerDelayPedestal[2]: !<value> 123
        - triggerWidthPedestal[2]: !<value> 18
#Channel 3 CBLM:UNDH:3675
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[6]: !<value> 0
        - IntegrationScaling[6]: !<value> 1
        - IntegrationDecay[7]: !<value> 0.99446
        - IntegrationScaling[7]: !<value> 1
        - triggerDelayPeak[3]: !<value> 1528
        - triggerWidthPeak[3]: !<value> 88
        - triggerDelayPedestal[3]: !<value> 61390
        - triggerWidthPedestal[3]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[6]: !<value> 0.999998
        - IntegrationScaling[6]: !<value> 1
        - IntegrationDecay[7]: !<value> 0
        - IntegrationScaling[7]: !<value> 1
        - triggerDelayPeak[3]: !<value> 21
        - triggerWidthPeak[3]: !<value> 18
        - triggerDelayPedestal[3]: !<value> 123
        - triggerWidthPedestal[3]: !<value> 18
#Channel 4 CBLM:UNDH:3775
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[8]: !<value> 0
        - IntegrationScaling[8]: !<value> 1
        - IntegrationDecay[9]: !<value> 0.99446
        - IntegrationScaling[9]: !<value> 1
        - triggerDelayPeak[4]: !<value> 1528
        - triggerWidthPeak[4]: !<value> 88
        - triggerDelayPedestal[4]: !<value> 61390
        - triggerWidthPedestal[4]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[8]: !<value> 0.999998
        - IntegrationScaling[8]: !<value> 1
        - IntegrationDecay[9]: !<value> 0
        - IntegrationScaling[9]: !<value> 1
        - triggerDelayPeak[4]: !<value> 21
        - triggerWidthPeak[4]: !<value> 18
        - triggerDelayPedestal[4]: !<value> 123
        - triggerWidthPedestal[4]: !<value> 18
#Channel 5 CBLM:UNDH:3875
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[10]: !<value> 0
        - IntegrationScaling[10]: !<value> 1
        - IntegrationDecay[11]: !<value> 0.99446
        - IntegrationScaling[11]: !<value> 1
        - triggerDelayPeak[5]: !<value> 1522
        - triggerWidthPeak[5]: !<value> 88
        - triggerDelayPedestal[5]: !<value> 61390
        - triggerWidthPedestal[5]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[10]: !<value> 0.999998
        - IntegrationScaling[10]: !<value> 1
        - IntegrationDecay[11]: !<value> 0
        - IntegrationScaling[11]: !<value> 1
        - triggerDelayPeak[5]: !<value> 19
        - triggerWidthPeak[5]: !<value> 18
        - triggerDelayPedestal[5]: !<value> 123
        - triggerWidthPedestal[5]: !<value> 18