## Load configurations
- AppTop:
    - AppCore:
        - MpsLinkNodeCore:
            - MpsMitigationCore:
                - mpsConfig: !<value> 0x3
#Analog Processing Settings
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationCounts[0]: !<value> 2
