#Channel 0 CBLM:UNDS:2210
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[0]: !<value> 0
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0.99446
        - IntegrationScaling[1]: !<value> 1
        - triggerDelayPeak[0]: !<value> 1649
        - triggerWidthPeak[0]: !<value> 88
        - triggerDelayPedestal[0]: !<value> 61390
        - triggerWidthPedestal[0]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[0]: !<value> 0.999998
        - IntegrationScaling[0]: !<value> 1
        - IntegrationDecay[1]: !<value> 0
        - IntegrationScaling[1]: !<value> 1
        - triggerDelayPeak[0]: !<value> 13
        - triggerWidthPeak[0]: !<value> 18
        - triggerDelayPedestal[0]: !<value> 123
        - triggerWidthPedestal[0]: !<value> 18
#Channel 1 CBLM:UNDS:2310
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[2]: !<value> 0
        - IntegrationScaling[2]: !<value> 1
        - IntegrationDecay[3]: !<value> 0.99446
        - IntegrationScaling[3]: !<value> 1
        - triggerDelayPeak[1]: !<value> 1649
        - triggerWidthPeak[1]: !<value> 88
        - triggerDelayPedestal[1]: !<value> 61390
        - triggerWidthPedestal[1]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[2]: !<value> 0.999998
        - IntegrationScaling[2]: !<value> 1
        - IntegrationDecay[3]: !<value> 0
        - IntegrationScaling[3]: !<value> 1
        - triggerDelayPeak[1]: !<value> 18
        - triggerWidthPeak[1]: !<value> 18
        - triggerDelayPedestal[1]: !<value> 123
        - triggerWidthPedestal[1]: !<value> 18
#Channel 2 CBLM:UNDS:2410
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[4]: !<value> 0
        - IntegrationScaling[4]: !<value> 1
        - IntegrationDecay[5]: !<value> 0.99446
        - IntegrationScaling[5]: !<value> 1
        - triggerDelayPeak[2]: !<value> 1649
        - triggerWidthPeak[2]: !<value> 88
        - triggerDelayPedestal[2]: !<value> 61390
        - triggerWidthPedestal[2]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[4]: !<value> 0.999998
        - IntegrationScaling[4]: !<value> 1
        - IntegrationDecay[5]: !<value> 0
        - IntegrationScaling[5]: !<value> 1
        - triggerDelayPeak[2]: !<value> 26
        - triggerWidthPeak[2]: !<value> 18
        - triggerDelayPedestal[2]: !<value> 123
        - triggerWidthPedestal[2]: !<value> 18
#Channel 3 CBLM:UNDS:2510
- AppTop:
  - AppCore:
    - MpsAnalogCore:
      - MpsAnalogLcls1Reg:
        - IntegrationDecay[6]: !<value> 0
        - IntegrationScaling[6]: !<value> 1
        - IntegrationDecay[7]: !<value> 0.99446
        - IntegrationScaling[7]: !<value> 1
        - triggerDelayPeak[3]: !<value> 1649
        - triggerWidthPeak[3]: !<value> 88
        - triggerDelayPedestal[3]: !<value> 61390
        - triggerWidthPedestal[3]: !<value> 175
      - MpsAnalogLcls2Reg:
        - IntegrationDecay[6]: !<value> 0.999998
        - IntegrationScaling[6]: !<value> 1
        - IntegrationDecay[7]: !<value> 0
        - IntegrationScaling[7]: !<value> 1
        - triggerDelayPeak[3]: !<value> 26
        - triggerWidthPeak[3]: !<value> 18
        - triggerDelayPedestal[3]: !<value> 123
        - triggerWidthPedestal[3]: !<value> 18
