## Load mitigation configurations
- AppTop:
    - AppCore:
        - MpsLinkNodeCore:
            - MpsMitigationCore:
                - mpsConfig: !<value> 0x0
                - mpsRtmDest[0]: !<value> 0x1
                - mpsRtmDest[1]: !<value> 0x1
                - mpsRtmDest[2]: !<value> 0x1
                - mpsRtmDest[3]: !<value> 0x1
